[package]
name = "unilang_parser"
version = "0.36.0"
edition = "2021"
license = "MIT"
readme = "readme.md"
authors = [ "Kostiantyn Mysnyk <wandalen@obox.systems>" ]
categories = [ "parsing", "command-line-interface" ]
keywords = [ "parser", "cli", "unilang", "instructions" ]
description = """
Parser for Unilang CLI instruction syntax.
"""
documentation = "https://docs.rs/unilang_parser"
repository = "https://github.com/Wandalen/unilang/tree/master/module/unilang_parser"
homepage = "https://github.com/Wandalen/unilang/tree/master/module/unilang_parser/readme.md"

[features]
default = [
  "enabled",
  "simd",
]
simd = ["enabled", "strs_tools/simd"]  # SIMD optimizations enabled by default, disable with --no-default-features
no_std = []


enabled = ["dep:strs_tools", "dep:error_tools", "dep:iter_tools"]
full = [
  "enabled",
  "simd",
]

[dependencies]
strs_tools = { workspace = true, features = ["std", "string_parse_request", "string_split"], optional = true }
error_tools = { workspace = true, features = [ "enabled", "error_typed" ], optional = true }
iter_tools = { workspace = true, features = [ "enabled" ], optional = true }

[dev-dependencies]
test_tools = { workspace = true, features = [ "full" ] }



