//! Static command map with PHF-based lookup.

use super::*;

  ///
  /// Wrapper for static command maps with zero-overhead compile-time lookup.
  ///
  /// This struct provides optimized O(1) command lookup using compile-time
  /// generated lookup tables. Downstream crates have zero additional dependencies.
  ///
  /// ## Performance
  ///
  /// - Lookup: O(1) with ~80ns overhead
  /// - Memory: Zero runtime allocation (compile-time data)
  /// - Binary size: Minimal (<1KB per 100 commands)
  ///
  /// ## Usage
  ///
  /// ```text
  /// // Generated by build.rs
  /// pub static STATIC_COMMANDS: StaticCommandMap = /* ... */;
  ///
  /// // Access commands
  /// if let Some(cmd) = STATIC_COMMANDS.get(".help") {
  ///   println!("Command: {}", cmd.name);
  /// }
  /// ```
  #[ derive( Debug ) ]
  pub struct StaticCommandMap
  {
    /// Internal optimized map - implementation detail, never exposed in public API
    inner: &'static phf::Map< &'static str, &'static StaticCommandDefinition >,
  }

  impl StaticCommandMap
  {
    /// Create from internal optimized map (internal use only by generated code).
    ///
    /// This method is hidden from documentation and should only be called
    /// by code generated in build.rs.
    #[ doc( hidden ) ]
    #[ inline ]
    pub const fn from_phf_internal( map: &'static phf::Map< &'static str, &'static StaticCommandDefinition > ) -> Self
    {
      Self { inner: map }
    }

    /// Get a command definition by name.
    ///
    /// Returns `Some(&StaticCommandDefinition)` if found, `None` otherwise.
    ///
    /// ## Performance
    ///
    /// O(1) operation using perfect hash lookup (~80ns).
    #[ inline ]
    #[ must_use ]
    pub fn get( &self, name: &str ) -> Option< &'static StaticCommandDefinition >
    {
      self.inner.get( name ).copied()
    }

    /// Check if a command exists in the map.
    #[ inline ]
    #[ must_use ]
    pub fn contains_key( &self, name: &str ) -> bool
    {
      self.inner.contains_key( name )
    }

    /// Get an iterator over all command names.
    pub fn keys( &self ) -> impl Iterator< Item = &&'static str >
    {
      self.inner.keys()
    }

    /// Get an iterator over all (name, definition) pairs.
    pub fn entries( &self ) -> impl Iterator< Item = (&&'static str, &&'static StaticCommandDefinition) >
    {
      self.inner.entries()
    }

    /// Get an iterator over all command definitions.
    pub fn values( &self ) -> impl Iterator< Item = &&'static StaticCommandDefinition >
    {
      self.inner.values()
    }

    /// Get the number of commands in the map.
    #[ inline ]
    #[ must_use ]
    pub fn len( &self ) -> usize
    {
      self.inner.len()
    }

    /// Check if the map is empty.
    #[ inline ]
    #[ must_use ]
    pub fn is_empty( &self ) -> bool
    {
      self.inner.is_empty()
    }
  }

  impl std::ops::Index< &str > for StaticCommandMap
  {
    type Output = &'static StaticCommandDefinition;

    /// Index access panics if key not found - use `get()` for safe access.
    fn index( &self, name: &str ) -> &Self::Output
    {
      self.inner.get( name )
        .unwrap_or_else( || panic!( "Command '{}' not found in static map", name ) )
    }
  }
