//!
//! Static Command Definitions - Compile-time optimized command metadata
//!
//! This module provides `const`-compatible data structures for defining commands
//! at compile time, enabling zero-overhead command lookup via Perfect Hash Functions (PHF).
//!
//! # Purpose
//!
//! Static command definitions solve the problem of runtime command registration overhead
//! by moving command metadata into the binary at compile time. This provides:
//!
//! - **Zero Runtime Cost**: Commands are pre-compiled into the binary
//! - **O(1) Lookup**: PHF maps provide constant-time command resolution (~80ns)
//! - **Type Safety**: Compile-time validation of command structure
//! - **Memory Efficiency**: Shared static data, no heap allocations
//!
//! # Architecture: Three-Layer Data Integrity Chain
//!
//! Static command definitions flow through three transformation layers:
//!
//! ```text
//! YAML Definition → Build Script (build.rs) → Static Struct → Dynamic Conversion
//!        ↓                    ↓                     ↓                ↓
//!   auto_help: true    extract field         store in PHF    preserve in CommandDefinition
//! ```
//!
//! **ALL THREE LAYERS MUST BE COMPLETE** for field values to reach runtime. Breaking
//! any link results in silent data loss (see Known Pitfalls below).
//!
//! # Usage
//!
//! Static commands are typically generated by `build.rs` from YAML manifests:
//!
//! ```yaml
//! # commands.yaml
//! commands:
//!   - name: .example
//!     description: Example command
//!     auto_help_enabled: true
//! ```
//!
//! Generated code:
//! ```text
//! const CMD: StaticCommandDefinition = StaticCommandDefinition {
//!   name: ".example",
//!   description: "Example command",
//!   auto_help_enabled: true,  // Extracted from YAML
//!   // ... other fields
//! };
//! ```
//!
//! Conversion to dynamic at runtime:
//! ```text
//! let dynamic_cmd: CommandDefinition = (&static_cmd).into();
//! assert!(dynamic_cmd.auto_help_enabled()); // Must be preserved
//! ```
//!
//! # Known Pitfalls
//!
//! ## Pitfall: Silent Field Loss in Conversions (BUG-088)
//!
//! **Problem**: Adding a new field to `StaticCommandDefinition` requires updates in
//! THREE separate locations. Missing any location causes silent data loss:
//!
//! 1. **Struct Definition** - Add field to `StaticCommandDefinition`
//! 2. **Build Script** - Extract field from YAML in `build.rs::generate_command_const()`
//! 3. **Conversion** - Map field in `From<&StaticCommandDefinition> for CommandDefinition`
//!
//! **Example**: The `auto_help_enabled` field was initially missing from the struct,
//! causing the conversion to hardcode `false` and breaking `.command.help` generation
//! for all static commands.
//!
//! **Impact**: User YAML configuration silently ignored, no compile-time or runtime errors,
//! just missing functionality. Affects ALL users of StaticCommandRegistry.
//!
//! **Prevention**:
//! - Add comprehensive conversion tests for new fields (see `tests/data/static_data.rs`)
//! - Use systematic field validation, not ad-hoc selection
//! - Mark critical tests with `// test_kind: bug_reproducer(BUG-NNN)`
//! - Document field purpose and default values in struct definition
//!
//! **Detection**: Conversion tests in `tests/data/static_data.rs` validate that ALL
//! struct fields are preserved during static→dynamic conversion.
//!
//! ## Pitfall: Cascading Updates Required
//!
//! **Problem**: Adding a field requires updating 20+ test instances across the codebase.
//! Missing updates = compilation errors.
//!
//! **Locations to Update**:
//! - All `tests/registry/*.rs` files (PHF map tests)
//! - All `tests/parser/*.rs` files (conversion tests)
//! - All `examples/*.rs` files (documentation examples)
//!
//! **Prevention**: Run `cargo test --all-features` to catch all instances.
//!
//! # Design Decisions
//!
//! **Why &'static str instead of String?**
//! - Enables `const` construction (required for compile-time PHF generation)
//! - Zero heap allocations, all data in .rodata section
//! - Shared across all command instances
//!
//! **Why separate from CommandDefinition?**
//! - CommandDefinition uses `String` and `Vec` (not const-compatible)
//! - Separation allows zero-cost static storage while maintaining ergonomic dynamic API
//! - Conversion happens once at registration, not per-command-invocation
//!

/// Internal namespace.
mod private
{
  ///
  /// Static, const-compatible version of `CommandDefinition`.
  ///
  /// Uses &'static str and &'static [...] instead of String and Vec
  /// to enable compile-time storage in optimized static registries.
  #[ derive( Debug, Clone ) ]
  pub struct StaticCommandDefinition
  {
    /// The name of the command, used to invoke it from the command line.
    pub name : &'static str,
    /// The namespace of the command.
    pub namespace : &'static str,
    /// A brief, one-line description of what the command does.
    pub description : &'static str,
    /// A short hint for the command.
    pub hint : &'static str,
    /// A list of arguments that the command accepts.
    pub arguments : &'static [ StaticArgumentDefinition ],
    /// An optional link to the routine that executes this command.
    pub routine_link : Option< &'static str >,
    /// The status of the command.
    pub status : &'static str,
    /// The version of the command.
    pub version : &'static str,
    /// Tags associated with the command.
    pub tags : &'static [ &'static str ],
    /// Aliases for the command.
    pub aliases : &'static [ &'static str ],
    /// Permissions required to execute the command.
    pub permissions : &'static [ &'static str ],
    /// Indicates if the command is idempotent.
    pub idempotent : bool,
    /// If `status` is `Deprecated`, explains the reason and suggests alternatives.
    pub deprecation_message : &'static str,
    /// A suggested HTTP method (`GET`, `POST`, etc.) for the Web API modality.
    pub http_method_hint : &'static str,
    /// Illustrative usage examples for help text.
    pub examples : &'static [ &'static str ],
    /// Whether to automatically generate a `.command.help` variant.
    ///
    /// When `true` (default), registering this command will automatically generate
    /// a corresponding `.command.help` variant. Set to `false` for help commands
    /// themselves to prevent recursive help generation.
    pub auto_help_enabled : bool,
    /// Category for grouping commands in help output.
    ///
    /// Commands with the same category are displayed together in help text.
    /// Empty string means no specific category (will be shown in default section).
    pub category : &'static str,
    /// Control whether version is displayed in help output.
    ///
    /// When `true` (default), version is shown in help text.
    /// Set to `false` to hide version from help output.
    pub show_version_in_help : bool,
  }

  impl StaticCommandDefinition
  {
    /// Creates a new `StaticCommandDefinition` with required fields and sensible defaults.
    ///
    /// # Examples
    ///
    /// ```rust
    /// use unilang::static_data::StaticCommandDefinition;
    ///
    /// const CMD: StaticCommandDefinition = StaticCommandDefinition::new(
    ///   ".greet",
    ///   "",
    ///   "Greets the user",
    /// );
    /// assert_eq!( CMD.name, ".greet" );
    /// ```
    #[ must_use ]
    pub const fn new(
      name : &'static str,
      namespace : &'static str,
      description : &'static str,
    ) -> Self
    {
      Self
      {
        name,
        namespace,
        description,
        hint : "",
        arguments : &[],
        routine_link : None,
        status : "stable",
        version : "1.0.0",
        tags : &[],
        aliases : &[],
        permissions : &[],
        idempotent : true,
        deprecation_message : "",
        http_method_hint : "GET",
        examples : &[],
        auto_help_enabled : true, // Default: enable automatic .command.help generation
        category : "", // Default: no specific category
        show_version_in_help : true, // Default: show version in help output
      }
    }

    /// Sets the hint for the command.
    #[ must_use ]
    pub const fn with_hint( mut self, hint : &'static str ) -> Self
    {
      self.hint = hint;
      self
    }

    /// Sets the arguments for the command.
    #[ must_use ]
    pub const fn with_arguments( mut self, arguments : &'static [ StaticArgumentDefinition ] ) -> Self
    {
      self.arguments = arguments;
      self
    }

    /// Sets the routine link for the command.
    #[ must_use ]
    pub const fn with_routine_link( mut self, routine_link : &'static str ) -> Self
    {
      self.routine_link = Some( routine_link );
      self
    }

    /// Sets the status for the command.
    #[ must_use ]
    pub const fn with_status( mut self, status : &'static str ) -> Self
    {
      self.status = status;
      self
    }

    /// Sets the version for the command.
    #[ must_use ]
    pub const fn with_version( mut self, version : &'static str ) -> Self
    {
      self.version = version;
      self
    }

    /// Sets the tags for the command.
    #[ must_use ]
    pub const fn with_tags( mut self, tags : &'static [ &'static str ] ) -> Self
    {
      self.tags = tags;
      self
    }

    /// Sets the aliases for the command.
    #[ must_use ]
    pub const fn with_aliases( mut self, aliases : &'static [ &'static str ] ) -> Self
    {
      self.aliases = aliases;
      self
    }

    /// Sets the permissions for the command.
    #[ must_use ]
    pub const fn with_permissions( mut self, permissions : &'static [ &'static str ] ) -> Self
    {
      self.permissions = permissions;
      self
    }

    /// Sets whether the command is idempotent.
    #[ must_use ]
    pub const fn with_idempotent( mut self, idempotent : bool ) -> Self
    {
      self.idempotent = idempotent;
      self
    }

    /// Sets the deprecation message for the command.
    #[ must_use ]
    pub const fn with_deprecation_message( mut self, deprecation_message : &'static str ) -> Self
    {
      self.deprecation_message = deprecation_message;
      self
    }

    /// Sets the HTTP method hint for the command.
    #[ must_use ]
    pub const fn with_http_method_hint( mut self, http_method_hint : &'static str ) -> Self
    {
      self.http_method_hint = http_method_hint;
      self
    }

    /// Sets the examples for the command.
    #[ must_use ]
    pub const fn with_examples( mut self, examples : &'static [ &'static str ] ) -> Self
    {
      self.examples = examples;
      self
    }

    /// Sets whether to automatically generate a `.command.help` variant.
    ///
    /// When `true` (default), registering this command will automatically generate
    /// a corresponding `.command.help` variant. Set to `false` for help commands
    /// themselves to prevent recursive help generation.
    #[ must_use ]
    pub const fn with_auto_help_enabled( mut self, enabled : bool ) -> Self
    {
      self.auto_help_enabled = enabled;
      self
    }

    /// Sets the category for the command.
    #[ must_use ]
    pub const fn with_category( mut self, category : &'static str ) -> Self
    {
      self.category = category;
      self
    }

    /// Sets whether version is displayed in help output.
    ///
    /// When `true` (default), version is shown in help text.
    /// Set to `false` to hide version from help output.
    #[ must_use ]
    pub const fn with_show_version_in_help( mut self, show : bool ) -> Self
    {
      self.show_version_in_help = show;
      self
    }
  }


  mod argument_types;
  pub use argument_types::{ StaticArgumentDefinition, StaticArgumentAttributes };

  ///
  /// Static, const-compatible version of Kind.
  ///
  #[ derive( Debug, Clone, Copy ) ]
  pub enum StaticKind
  {
    /// A simple text string.
    String,
    /// An integer number.
    Integer,
    /// A floating-point number.
    Float,
    /// A boolean value.
    Boolean,
    /// A file system path.
    Path,
    /// A file system path that must point to an existing file.
    File,
    /// A file system path that must point to an existing directory.
    Directory,
    /// An enumeration with a predefined set of allowed values.
    Enum( &'static [ &'static str ] ),
    /// A URL (web address).
    Url,
    /// A date and time value.
    DateTime,
    /// A regular expression pattern.
    Pattern,
    /// A list (array) of values of the same type.
    List( &'static StaticKind, Option< char > ),
    /// A map (dictionary) of key-value pairs.
    Map( &'static StaticKind, &'static StaticKind, Option< char >, Option< char > ),
    /// A JSON string.
    JsonString,
    /// A generic object.
    Object,
  }

  ///
  /// Static, const-compatible version of `ValidationRule`.
  ///
  #[ derive( Debug, Clone, Copy ) ]
  pub enum StaticValidationRule
  {
    /// Minimum value for numeric types.
    Min( f64 ),
    /// Maximum value for numeric types.
    Max( f64 ),
    /// Minimum length for string types.
    MinLength( usize ),
    /// Maximum length for string types.
    MaxLength( usize ),
    /// Pattern that string values must match.
    Pattern( &'static str ),
    /// Minimum number of items for collection types.
    MinItems( usize ),
  }


  mod command_map;
  pub use command_map::StaticCommandMap;

  mod conversions;

}

mod_interface::mod_interface!
{
  exposed use private::StaticCommandDefinition;
  exposed use private::StaticArgumentDefinition;
  exposed use private::StaticArgumentAttributes;
  exposed use private::StaticKind;
  exposed use private::StaticValidationRule;
  exposed use private::StaticCommandMap;

  prelude use private::StaticCommandDefinition;
  prelude use private::StaticArgumentDefinition;
  prelude use private::StaticArgumentAttributes;
  prelude use private::StaticKind;
  prelude use private::StaticValidationRule;
  prelude use private::StaticCommandMap;
}