use crate::data::CommandDefinition;
use crate::error::Error;
use std::collections::HashMap;
use super::map::DynamicCommandMap;
use super::metrics::PerformanceMetrics;
use super::traits::{ CommandRoutine, RegistryMode, format_command_help };

///
/// Static command registry with hybrid lookup functionality.
///
/// **Requires feature**: `static_registry` (automatically enabled by approach features like
/// `approach_yaml_single_build`, `approach_yaml_multi_build`, `approach_rust_dsl_const`, etc.)
///
/// Provides optimal performance through compile-time optimized static maps (using PHF)
/// for static commands while supporting dynamic runtime commands as fallback.
/// Static commands always take priority for predictable performance characteristics.
///
/// ## Performance Characteristics
///
/// - **Static command lookup**: O(1), typically ~80-100ns per operation
///   - Uses Perfect Hash Functions (PHF) for zero-overhead lookups
///   - Zero heap allocations during lookup
///   - 50x faster than runtime `CommandRegistry` (~4,000ns)
/// - **Dynamic command lookup**: O(1) average case with LRU caching, ~4,000ns
/// - **Hybrid mode**: Prioritizes static commands for optimal hot path performance
///
/// ## Recommended Usage Pattern
///
/// **DO NOT manually construct static maps!** Instead, use YAML + build system:
///
/// ```ignore
/// // In your project:
/// // 1. Create unilang.commands.yaml with command definitions
/// // 2. Add feature to Cargo.toml: unilang = "0.28" (default enables multi-YAML)
/// // 3. Include generated static commands:
///
/// include!(concat!(env!("OUT_DIR"), "/static_commands.rs"));
///
/// // 4. Use the generated STATIC_COMMANDS constant:
/// let registry = StaticCommandRegistry::from_commands(&STATIC_COMMANDS);
/// let pipeline = Pipeline::new(registry);
/// ```
///
/// See `examples/static_01_basic_compile_time.rs` for complete walkthrough.
///
/// ## Hybrid Mode Example
/// ```no_run
/// use unilang::registry::{StaticCommandRegistry, RegistryMode};
///
/// // Create registry with hybrid mode (default)
/// let mut registry = StaticCommandRegistry::new();
///
/// // Or create with specific mode
/// let mut static_only = StaticCommandRegistry::with_mode(RegistryMode::StaticOnly);
/// ```
pub struct StaticCommandRegistry {
  /// Compile-time optimized static command storage
  static_commands: Option<&'static crate::static_data::StaticCommandMap>,
  /// Dynamic command storage with intelligent caching
  dynamic_commands: DynamicCommandMap,
  /// Runtime command routines
  routines: HashMap<String, CommandRoutine>,
  /// Registry mode controlling lookup behavior
  mode: RegistryMode,
  /// Performance metrics for monitoring
  metrics: PerformanceMetrics,
}

impl std::fmt::Debug for StaticCommandRegistry
{
  fn fmt( &self, f : &mut std::fmt::Formatter< '_ > ) -> std::fmt::Result
  {
    f.debug_struct( "StaticCommandRegistry" )
      .field( "has_static_commands", &self.static_commands.is_some() )
      .field( "mode", &self.mode )
      .field( "metrics", &self.metrics )
      .field( "dynamic_commands", &self.dynamic_commands )
      .field( "routines_count", &self.routines.len() ) // CommandRoutine is Box<dyn Fn>, which doesn't impl Debug
      .finish()
  }
}

impl StaticCommandRegistry {
  /// Create a new static command registry with default hybrid mode.
  ///
  /// The registry will check static commands first, then fall back to
  /// dynamic commands for optimal performance.
  #[must_use]
  pub fn new() -> Self {
    Self {
      static_commands: None,
      dynamic_commands: DynamicCommandMap::new(RegistryMode::Hybrid),
      routines: HashMap::new(),
      mode: RegistryMode::Hybrid,
      metrics: PerformanceMetrics::default(),
    }
  }

  /// Create a static command registry with specific mode.
  ///
  /// # Arguments
  /// * `mode` - Registry operation mode controlling lookup behavior
  #[must_use]
  pub fn with_mode(mode: RegistryMode) -> Self {
    Self {
      static_commands: None,
      dynamic_commands: DynamicCommandMap::new(mode),
      routines: HashMap::new(),
      mode,
      metrics: PerformanceMetrics::default(),
    }
  }

  /// Create a static command registry from a static command map.
  ///
  /// This method initializes the registry with compile-time generated commands
  /// for zero-overhead lookups (~80ns per command).
  ///
  /// # Arguments
  /// * `commands` - Static command map (typically `&STATIC_COMMANDS` from generated code)
  ///
  /// # Examples
  /// ```ignore
  /// // STATIC_COMMANDS generated by build.rs
  /// let registry = StaticCommandRegistry::from_commands(&STATIC_COMMANDS);
  /// ```
  #[must_use]
  pub fn from_commands(commands: &'static crate::static_data::StaticCommandMap) -> Self {
    Self {
      static_commands: Some(commands),
      dynamic_commands: DynamicCommandMap::new(RegistryMode::Hybrid),
      routines: HashMap::new(),
      mode: RegistryMode::Hybrid,
      metrics: PerformanceMetrics::default(),
    }
  }

  /// Get a command definition using hybrid lookup with performance tracking.
  ///
  /// Lookup strategy depends on registry mode:
  /// - StaticOnly: Static registry only
  /// - DynamicOnly: Dynamic commands only
  /// - Hybrid: Static first, then dynamic fallback
  /// - Auto: Usage pattern optimization
  #[must_use]
  pub fn command_with_metrics(&mut self, name: &str) -> Option<CommandDefinition> {
    self.metrics.total_lookups += 1;

    match self.mode {
      RegistryMode::StaticOnly => {
        if let Some(static_commands) = &self.static_commands {
          if let Some(static_cmd) = static_commands.get(name) {
            self.metrics.static_lookups += 1;
            Some(static_cmd.into())
          } else {
            None
          }
        } else {
          None
        }
      }
      RegistryMode::DynamicOnly => {
        self.dynamic_commands.get(name)
      }
      RegistryMode::Hybrid | RegistryMode::Auto => {
        // Static commands take priority for performance
        if let Some(static_commands) = &self.static_commands {
          if let Some(static_cmd) = static_commands.get(name) {
            self.metrics.static_lookups += 1;
            Some(static_cmd.into())
          } else {
            // Fall back to dynamic commands
            self.dynamic_commands.get(name)
          }
        } else {
          // No static commands available, use dynamic only
          self.dynamic_commands.get(name)
        }
      }
    }
  }

  /// Get a command definition (immutable access for compatibility with CommandRegistry).
  ///
  /// This provides the same interface as CommandRegistry::command() for components
  /// like SemanticAnalyzer that require immutable registry access.
  #[must_use]
  pub fn command(&self, name: &str) -> Option<CommandDefinition> {
    self.command_readonly(name)
  }

  /// Get a command definition without updating metrics (immutable access).
  #[must_use]
  pub fn command_readonly(&self, name: &str) -> Option<CommandDefinition> {
    match self.mode {
      RegistryMode::StaticOnly => {
        self.static_commands.as_ref().and_then( | m | m.get( name ).map( | c | c.into() ) )
      }
      RegistryMode::DynamicOnly => {
        self.dynamic_commands.get_readonly(name)
      }
      RegistryMode::Hybrid | RegistryMode::Auto => {
        // Static commands take priority
        if let Some(static_commands) = &self.static_commands {
          if let Some(static_cmd) = static_commands.get(name) {
            Some(static_cmd.into())
          } else {
            self.dynamic_commands.get_readonly(name)
          }
        } else {
          // No static commands available, use dynamic only
          self.dynamic_commands.get_readonly(name)
        }
      }
    }
  }

  /// Register a dynamic command.
  ///
  /// Note: Static commands always take priority in hybrid mode.
  /// Dynamic commands with same names as static commands will be shadowed.
  pub fn register(&mut self, command: CommandDefinition) {
    let full_name = command.full_name();
    self.dynamic_commands.insert(full_name, command);
  }

  /// Register a command with its executable routine.
  pub fn register_with_routine(&mut self, command: CommandDefinition, routine: CommandRoutine) -> Result<(), Error> {
    let full_name = command.full_name();
    self.routines.insert(full_name.clone(), routine);
    self.dynamic_commands.insert(full_name, command);
    Ok(())
  }

  /// Check if a command exists (static or dynamic).
  #[must_use]
  pub fn contains(&self, name: &str) -> bool {
    match self.mode {
      RegistryMode::StaticOnly => {
        if let Some(static_commands) = &self.static_commands {
          static_commands.contains_key(name)
        } else {
          false
        }
      }
      RegistryMode::DynamicOnly => {
        self.dynamic_commands.contains_key(name)
      }
      RegistryMode::Hybrid | RegistryMode::Auto => {
        let static_contains = if let Some(static_commands) = &self.static_commands {
          static_commands.contains_key(name)
        } else {
          false
        };
        static_contains || self.dynamic_commands.contains_key(name)
      }
    }
  }

  /// Get all static command names.
  #[must_use]
  pub fn static_commands(&self) -> Vec<String> {
    if matches!(self.mode, RegistryMode::DynamicOnly) {
      Vec::new()
    } else if let Some(static_commands) = &self.static_commands {
      static_commands.keys().map(|k| (*k).to_string()).collect()
    } else {
      Vec::new()
    }
  }

  /// Get all dynamic command names.
  #[must_use]
  pub fn dynamic_commands(&self) -> Vec<String> {
    if matches!(self.mode, RegistryMode::StaticOnly) {
      Vec::new()
    } else {
      self.dynamic_commands.iter().map(|(k, _)| k.clone()).collect()
    }
  }

  /// Get all command names (static and dynamic).
  #[must_use]
  pub fn all_commands(&self) -> Vec<String> {
    let mut commands = self.static_commands();
    commands.extend(self.dynamic_commands());
    commands.sort();
    commands.dedup();
    commands
  }

  /// Get current registry mode.
  #[must_use]
  pub fn mode(&self) -> RegistryMode {
    self.mode
  }

  /// Set registry mode.
  pub fn set_mode(&mut self, mode: RegistryMode) {
    self.mode = mode;
    self.dynamic_commands.set_mode(mode);
  }

  /// Get performance metrics.
  #[must_use]
  pub fn performance_metrics(&self) -> &PerformanceMetrics {
    &self.metrics
  }

  /// Clear all dynamic commands and reset metrics.
  pub fn clear(&mut self) {
    self.dynamic_commands = DynamicCommandMap::new(self.mode);
    self.routines.clear();
    self.metrics = PerformanceMetrics::default();
  }

  /// Get command routine for execution.
  #[must_use]
  pub fn routine(&self, name: &str) -> Option<&CommandRoutine> {
    self.routines.get(name)
  }

  /// Get command routine for execution (alias for compatibility with CommandRegistry).
  #[must_use]
  pub fn get_routine(&self, name: &str) -> Option<&CommandRoutine> {
    self.routine(name)
  }

  /// Get all commands as a HashMap (for compatibility with CommandRegistry interface).
  ///
  /// This method provides the same interface as CommandRegistry::commands() for seamless
  /// integration with components like SemanticAnalyzer that expect this method.
  #[must_use]
  pub fn commands(&self) -> std::collections::HashMap<String, crate::data::CommandDefinition> {
    let mut all_commands = std::collections::HashMap::new();

    // Add static commands if not in DynamicOnly mode
    if !matches!(self.mode, RegistryMode::DynamicOnly) {
      if let Some(static_commands) = &self.static_commands {
        for (name, static_cmd) in static_commands.entries() {
          all_commands.insert((*name).to_string(), (*static_cmd).into());
        }
      }
    }

    // Add dynamic commands if not in StaticOnly mode
    if !matches!(self.mode, RegistryMode::StaticOnly) {
      for (name, cmd) in self.dynamic_commands.iter() {
        all_commands.insert(name.clone(), cmd.clone());
      }
    }

    all_commands
  }

  /// Get formatted help text for a command (for compatibility with CommandRegistry interface).
  ///
  /// This method provides the same interface as CommandRegistry::get_help_for_command()
  /// for seamless integration with Pipeline and other components.
  #[must_use]
  pub fn get_help_for_command(&self, command_name: &str) -> Option<String> {
    self.command_readonly(command_name).map( |cmd_def| self.format_help_text(&cmd_def) )
  }

  /// Format help text for a command definition (internal helper).
  fn format_help_text(&self, cmd_def: &crate::data::CommandDefinition) -> String {
    format_command_help( cmd_def )
  }

  /// Get number of static commands available.
  #[must_use]
  pub fn static_command_count(&self) -> usize {
    if matches!(self.mode, RegistryMode::DynamicOnly) {
      0
    } else if let Some(static_commands) = &self.static_commands {
      static_commands.len()
    } else {
      0
    }
  }

  /// Get number of dynamic commands registered.
  #[must_use]
  pub fn dynamic_command_count(&self) -> usize {
    if matches!(self.mode, RegistryMode::StaticOnly) {
      0
    } else {
      self.dynamic_commands.iter().count()
    }
  }

  /// Consume this registry and return its routines map.
  ///
  /// Used by `From<StaticCommandRegistry> for CommandRegistry` to transfer
  /// routines without cloning. For non-consuming access use `get_routine()`.
  #[ must_use ]
  pub fn into_routines( self ) -> HashMap< String, CommandRoutine >
  {
    self.routines
  }
}

impl Default for StaticCommandRegistry {
  fn default() -> Self {
    Self::new()
  }
}

impl super::traits::CommandRegistryTrait for StaticCommandRegistry {
  fn command(&self, name: &str) -> Option<crate::data::CommandDefinition> {
    self.command(name)
  }

  fn commands(&self) -> std::collections::HashMap<String, crate::data::CommandDefinition> {
    self.commands()
  }

  fn get_routine(&self, name: &str) -> Option<&CommandRoutine> {
    self.get_routine(name)
  }

  fn get_help_for_command(&self, command_name: &str) -> Option<String> {
    self.get_help_for_command(command_name)
  }
}
