//! Conflict detection and resolution for multi-YAML aggregation.

#[ allow( unused_imports ) ]
use crate::*;
use super::core::MultiYamlAggregator;
use super::core_types::{ ModuleConfig, ConflictReport, ConflictType, ConflictResolutionStrategy };
use std::collections::HashMap;

impl MultiYamlAggregator
{
  /// Detect conflicts across modules
  pub fn detect_conflicts( &mut self )
  {
    if !self.config.detect_conflicts
    {
      return;
    }

    let mut base_names: HashMap< String, Vec< String > > = HashMap::new();

    // Track which modules would generate the same base command names
    for module in &self.config.modules
    {
      if !module.enabled
      {
        continue;
      }

      // For each module, determine what base commands it would generate
      let base_commands = self.get_module_base_commands( module );

      for base_name in base_commands
      {
        base_names
          .entry( base_name )
          .or_default()
          .push( module.name.clone() );
      }
    }

    // Detect conflicts
    for ( cmd_name, sources ) in base_names
    {
      if sources.len() > 1
      {
        self.conflicts.push( ConflictReport
        {
          command_name: cmd_name,
          modules: sources,
          conflict_type: ConflictType::NameCollision,
        } );
      }
    }
  }

  /// Get base command names that would be generated by a module
  ///
  /// Parses the module's YAML file and extracts actual command names,
  /// applying module prefixes as configured to match how commands
  /// will be registered during `process_yaml_files()`.
  ///
  /// # Arguments
  /// * `module` - The module configuration containing YAML path and prefix
  ///
  /// # Returns
  /// * `Vec<String>` - List of full command names (with prefixes applied)
  ///   Returns empty vector if YAML parsing fails or module not loaded
  ///
  /// # Implementation Notes
  /// This function must mirror the prefix application logic in `process_yaml_files()`
  /// to ensure conflict detection matches actual registration.
  fn get_module_base_commands( &self, module: &ModuleConfig ) -> Vec< String >
  {
    // Load YAML content for this module
    let yaml_content = match self.yaml_files.get( &module.name )
    {
      Some( content ) => content,
      None =>
      {
        // Module YAML not loaded - this shouldn't happen if load_yaml_files() succeeded
        // but handle gracefully
        eprintln!( "Warning: YAML not loaded for module '{}' during conflict detection", module.name );
        return vec![];
      }
    };

    // Parse YAML to get command definitions
    let command_defs = match crate::load_command_definitions_from_yaml_str( yaml_content )
    {
      Ok( defs ) => defs,
      Err( e ) =>
      {
        // If YAML parsing fails, log warning but don't crash conflict detection
        // This allows other modules to be checked
        eprintln!( "Warning: Failed to parse YAML for module '{}': {}", module.name, e );
        return vec![];
      }
    };

    // Extract command names, applying prefixes to match registration logic
    command_defs.iter().map( |cmd|
    {
      // Start with command namespace and name
      let mut namespace = cmd.namespace().to_string();
      let name = cmd.name().as_str();

      // Apply module prefix if configured
      if let Some( prefix ) = &module.prefix
      {
        namespace = if namespace.is_empty()
        {
          format!( ".{}", prefix )
        }
        else
        {
          format!( ".{}{}", prefix, namespace )
        };
      }

      // Apply global prefix if configured
      if let Some( global_prefix ) = &self.config.global_prefix
      {
        namespace = if namespace.is_empty()
        {
          format!( ".{}", global_prefix )
        }
        else
        {
          format!( ".{}{}", global_prefix, namespace )
        };
      }

      // Construct full name using the same logic as process_yaml_files()
      if namespace.is_empty()
      {
        name.to_string()
      }
      else
      {
        // Construct full command name manually (same logic as in CommandDefinition::full_name())
        if namespace.starts_with( '.' )
        {
          format!( "{}.{}", namespace, name.trim_start_matches( '.' ) )
        }
        else
        {
          format!( ".{}.{}", namespace, name.trim_start_matches( '.' ) )
        }
      }
    } ).collect()
  }

  /// Resolve conflicts according to the configured strategy
  pub fn resolve_conflicts( &mut self ) -> Result< (), Error >
  {
    if self.conflicts.is_empty()
    {
      return Ok( () );
    }

    match self.config.conflict_resolution
    {
      ConflictResolutionStrategy::Fail =>
      {
        if !self.conflicts.is_empty()
        {
          let conflict_messages: Vec< String > = self.conflicts
            .iter()
            .map( |c| format!( "Command '{}' defined in modules: {:?}", c.command_name, c.modules ) )
            .collect();

          return Err( Error::Registration(
            format!( "Command conflicts detected:\n{}", conflict_messages.join( "\n" ) )
          ) );
        }
      }

      ConflictResolutionStrategy::UseFirst =>
      {
        // Remove later duplicates, keeping the first occurrence
        for conflict in &self.conflicts
        {
          // Find the first module that defines this command
          if let Some( _first_module ) = conflict.modules.first()
          {
            // Remove command definitions from other modules
            self.commands.retain( |name, _cmd| {
              if name == &conflict.command_name
              {
                // Only keep if it came from the first module
                // This is a simplified check - in a real implementation,
                // we'd track which module each command came from
                true // Keep for now, would need module tracking
              }
              else
              {
                true
              }
            } );
          }
        }
      }

      ConflictResolutionStrategy::UseLast =>
      {
        // Remove earlier duplicates, keeping the last occurrence
        // Similar logic but keeping the last instead of first
        // Implementation would be similar to UseFirst
      }

      ConflictResolutionStrategy::Merge =>
      {
        // Attempt to merge conflicting commands where possible
        // This would involve merging compatible command properties
        // Complex implementation would go here
      }
    }

    // Clear conflicts after resolution
    self.conflicts.clear();
    Ok( () )
  }
}
